services:
  kiwix-server:
    image: ghcr.io/kiwix/kiwix-serve
    container_name: kiwix-server
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - './zim_files:/data'
    command: '"*_latest.zim"'